# -*- coding: utf-8 -*-
"""DATA690_Assignment2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nxjd3JdggWSCowafYJSsvWKew-vozUw5

**EXERCISE**

The task involves prompting a user to input 10 integers. If the user enters anything other than integers such as a String value, an error message appears and allows the user to reenter. The 10 integers are displayed back to the user at the end. The second code provides descriptive stats on these 10 integers.
"""

#STEP 1: Prompt a user to enter 10 integers

#Creates an empty list
list1 = []

# Calls for a loop that keeps executing until 10 integers have been entered
# or until an exception occurs
while True:
    try:
      num = int(input('Enter Number:'))
      list1.append(num)
    # If something else that is not the string
    # version of a number is introduced, the
    # ValueError exception will be called
    except ValueError:
      print("Invalid Entry.You must enter an Integer Value only")
      continue
    if len(list1) == 10:
      #When succesful the loop will end.
      break
  
print(list1)

#STEP 2: Calcuate descriptive stats for list1

#a. Defining Variance function for subsequent use
def varx(list1, _Mean):
    sum = 0
    for num in list1:
        difference = num - _Mean
        square = difference ** 2
        sum = sum + square
        var = sum / (len(list1) - 1)
    return var

#b. Minimum
Min = min(list1)
print("Min:", Min)

#c. Maximum
Max = max(list1)
print("Max:", Max)

#d. Range
Range = Max - Min
print("Range:", Range)

#e. Mean
_Mean = sum(list1) / len(list1)
print("Mean:", _Mean)

#f. Standard Deviation
v = varx(list1, _Mean)
print("Variance:", v)

SD = v ** 0.5
print("Standard Deviation:", SD)