# -*- coding: utf-8 -*-
"""Assignment3_hwk

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/FeeshX/DATA-690-WANG/blob/master/Assignment3/Assignment3_hwk.ipynb

**Exercise**

The task involves writing a program that generates 100 random integers between 0 and 9, and subsequently performing certain actions around it as outlined in each step.
"""

#Print the numbers in a 10 by 10 matrix neatly arranged (one space between each number):
import random

matrix1 = [random.choices(range(0,10), k=10) for _ in range(10)]

for i in range(len(matrix1)): 
    for x in matrix1: 
        print(x[i], end =' ') 
    print()

##If the random number is an odd number, print "@" instead
# Function to update the array  

def searchlist(matrix1):
    for i, element in enumerate(matrix1):
        if isinstance(element,list):
            searchlist(element)
        elif (element % 2 != 0):
            element = '@'
            matrix1[i] = element

searchlist(matrix1)

for i in range(len(matrix1)): 
    for x in matrix1: 
        print(x[i], end =' ') 
    print()

#Calculate and print the total of each row (use "*" to separate the total from the numbers):
def column_sum(matrix1): 
      
     return [sum(j) for j in zip(*matrix1)] 
           
new_list = column_sum(matrix1)

matrix1.append(new_list)

matrix1.insert(len(matrix1) - 1, ['*', '*', '*', '*', '*', '*', '*', '*', '*', '*'])

for i in range(len(matrix1) - 2): 
  for x in matrix1:
    print(x[i], end= ' ') 
  print()